const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.CV_BoundedDragnDrop,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.AdvancedRandom,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.CV_BoundedDragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Behaviors.CV_BoundedDragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Tween.Acts.TweenTwoProperties
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{id: 0},
	{box: 0},
	{Physics: 0},
	{DragDrop: 0},
	{BoundedDragDrop: 0},
	{objects: 0},
	{solid: 0},
	{Touch: 0},
	{Solid: 0},
	{pass_through: 0},
	{Text: 0},
	{lighten: 0},
	{objects_d: 0},
	{objects_d2: 0},
	{locations: 0},
	{AdvancedRandom: 0},
	{Pin: 0},
	{objects_d3: 0},
	{objects_d4: 0},
	{Tween: 0},
	{glass: 0},
	{Browser: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	objects: class extends self.ISpriteInstance {},
	solid: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	pass_through: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lighten: class extends self.ISpriteInstance {},
	objects_d: class extends self.ISpriteInstance {},
	objects_d2: class extends self.ISpriteInstance {},
	locations: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	objects_d3: class extends self.ISpriteInstance {},
	objects_d4: class extends self.ISpriteInstance {},
	glass: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}