const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Tween.Exps.Value
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{bg: 0},
	{intro: 0},
	{type: 0},
	{color: 0},
	{hamm: 0},
	{ele: 0},
	{heat: 0},
	{id: 0},
	{Sine: 0},
	{Sine2: 0},
	{DragDrop: 0},
	{element: 0},
	{Touch: 0},
	{panel: 0},
	{clickable: 0},
	{electr: 0},
	{Keyboard: 0},
	{Text: 0},
	{vari: 0},
	{glow: 0},
	{dropPOS: 0},
	{digital: 0},
	{Particles: 0},
	{Back: 0},
	{Audio: 0},
	{Browser: 0},
	{Done: 0},
	{eleCon: 0},
	{heatCon: 0},
	{hammerFrame: 0},
	{posX1: 0},
	{posY1: 0},
	{posX2: 0},
	{posY2: 0},
	{posX3: 0},
	{posY3: 0},
	{posX4: 0},
	{posY4: 0},
	{posX5: 0},
	{posY5: 0},
	{posX6: 0},
	{posY6: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	intro: class extends self.ISpriteInstance {},
	element: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	panel: class extends self.ISpriteInstance {},
	hamm: class extends self.ISpriteInstance {},
	electr: class extends self.ISpriteInstance {},
	heat: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	vari: class extends self.ISpriteInstance {},
	glow: class extends self.ISpriteInstance {},
	dropPOS: class extends self.ISpriteInstance {},
	digital: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Back: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Done: class extends self.ITextInstance {}
}