const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Globals,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Globals.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Globals.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions
	];
};
self.C3_JsPropNameTable = [
	{backgroundStage2: 0},
	{DragDrop: 0},
	{Tween: 0},
	{animals_stage2: 0},
	{id: 0},
	{s2: 0},
	{Pin: 0},
	{Stage2_target: 0},
	{stud_name: 0},
	{correct: 0},
	{is_0: 0},
	{is_1: 0},
	{is_2: 0},
	{is_3: 0},
	{is_4: 0},
	{is_5: 0},
	{st1_level: 0},
	{st1_choose: 0},
	{Globals: 0},
	{Rotate: 0},
	{hint: 0},
	{backgroundStage1: 0},
	{zoom_eff: 0},
	{glass: 0},
	{check: 0},
	{Touch: 0},
	{info_ui: 0},
	{Sprite2: 0},
	{animals: 0},
	{animals_x: 0},
	{xray: 0},
	{xray_eff: 0},
	{Button: 0},
	{TextInput: 0},
	{group: 0},
	{Group: 0},
	{Variable1: 0},
	{group1: 0},
	{group2: 0},
	{group3: 0},
	{group4: 0},
	{stud_num: 0},
	{names: 0},
	{AdvancedRandom: 0},
	{results1: 0},
	{Text: 0},
	{counter: 0},
	{count: 0},
	{Browser: 0}
];

self.InstanceType = {
	backgroundStage2: class extends self.ISpriteInstance {},
	animals_stage2: class extends self.ISpriteInstance {},
	Stage2_target: class extends self.ISpriteInstance {},
	stud_name: class extends self.ITextInstance {},
	Globals: class extends self.IInstance {},
	hint: class extends self.ISpriteInstance {},
	backgroundStage1: class extends self.ISpriteInstance {},
	zoom_eff: class extends self.ISpriteInstance {},
	glass: class extends self.ISpriteInstance {},
	check: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	info_ui: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	animals: class extends self.ISpriteInstance {},
	animals_x: class extends self.ISpriteInstance {},
	xray: class extends self.ISpriteInstance {},
	xray_eff: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	TextInput: class extends self.ITextInputInstance {},
	group: class extends self.ITextInstance {},
	names: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	results1: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	count: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {}
}