var pos = document.URL.indexOf('?', 0) + 1;
var mediaURL = document.URL.substr(pos);
var MediaID = mediaURL.substr(8);
var MediaTitle = MediaID.substr(0, MediaID.length - 4);

document.writeln('<html>');
document.writeln('<head>');
document.writeln('<title>eScience ' + MediaTitle + '</title>');
document.writeln('<style>');
document.writeln('html, body { margin:0; padding:0; width:100%; height:100%; overflow:hidden; background:#000; }');
document.writeln('#flash-container { position:absolute; top:0; left:0; width:100%; height:100%; }');
document.writeln('#flash-object { display:block; }');
document.writeln('</style>');
document.writeln('<script>');
document.writeln('function resizeFlash() {');
document.writeln('    var container = document.getElementById("flash-container");');
document.writeln('    var flashObj = document.getElementById("CONTAINER");');
document.writeln('    var embedObj = document.getElementById("flash-embed");');
document.writeln('    ');
document.writeln('    var windowWidth = window.innerWidth;');
document.writeln('    var windowHeight = window.innerHeight;');
document.writeln('    var aspectRatio = 4/3; // نسبة الشاشة 4:3 (عدلها حسب محتواك)');
document.writeln('    ');
document.writeln('    var newWidth = windowWidth;');
document.writeln('    var newHeight = windowWidth / aspectRatio;');
document.writeln('    ');
document.writeln('    if (newHeight > windowHeight) {');
document.writeln('        newHeight = windowHeight;');
document.writeln('        newWidth = windowHeight * aspectRatio;');
document.writeln('    }');
document.writeln('    ');
document.writeln('    if (flashObj) {');
document.writeln('        flashObj.style.width = newWidth + "px";');
document.writeln('        flashObj.style.height = newHeight + "px";');
document.writeln('        flashObj.style.position = "absolute";');
document.writeln('        flashObj.style.left = (windowWidth - newWidth) / 2 + "px";');
document.writeln('        flashObj.style.top = (windowHeight - newHeight) / 2 + "px";');
document.writeln('    }');
document.writeln('    ');
document.writeln('    if (embedObj) {');
document.writeln('        embedObj.style.width = newWidth + "px";');
document.writeln('        embedObj.style.height = newHeight + "px";');
document.writeln('        embedObj.style.position = "absolute";');
document.writeln('        embedObj.style.left = 0 + "px";');
document.writeln('        embedObj.style.top = 0 + "px";');
document.writeln('    }');
document.writeln('}');
document.writeln('');
document.writeln('window.onload = resizeFlash;');
document.writeln('window.onresize = resizeFlash;');
document.writeln('</script>');
document.writeln('</head>');
document.writeln('<body onload="resizeFlash()">');
document.writeln('<div id="flash-container">');
document.writeln('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" id="CONTAINER" align="middle">');
document.writeln('<param name="movie" value="container.swf?MediaID=' + MediaID + '" />');
document.writeln('<param name="quality" value="high" />');
document.writeln('<param name="allowScriptAccess" value="sameDomain" />');
document.writeln('<param name="scale" value="noscale" />');
document.writeln('<param name="bgcolor" value="#000000" />');
document.writeln('<param name="wmode" value="opaque" />');
document.writeln('<embed id="flash-embed" src="container.swf?MediaID=' + MediaID + '" quality="high" scale="noscale" bgcolor="#000000" wmode="opaque" name="container" align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" allowScriptAccess="sameDomain" />');
document.writeln('</object>');
document.writeln('</div>');
document.writeln('</body>');
document.writeln('</html>');