var pos = document.URL.indexOf('?', 0) + 1;
var mediaURL = document.URL.substr(pos);
var MediaID = mediaURL.substr(8);
var MediaTitle = MediaID.substr(0, MediaID.length - 4);

// الأبعاد الافتراضية (يمكن تعديلها حسب محتواك)
var defaultWidth = 1024;
var defaultHeight = 768;
var aspectRatio = defaultWidth / defaultHeight;

document.writeln('<!DOCTYPE html>');
document.writeln('<html lang="ar">');
document.writeln('<head>');
document.writeln('    <meta charset="UTF-8">');
document.writeln('    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">');
document.writeln('    <title>eScience - ' + MediaTitle + '</title>');
document.writeln('    <style>');
document.writeln('        * { margin: 0; padding: 0; box-sizing: border-box; }');
document.writeln('        html, body {');
document.writeln('            width: 100%;');
document.writeln('            height: 100%;');
document.writeln('            overflow: hidden;');
document.writeln('            background-color: #000;');
document.writeln('            font-family: Arial, sans-serif;');
document.writeln('        }');
document.writeln('        #flash-wrapper {');
document.writeln('            position: fixed;');
document.writeln('            top: 0;');
document.writeln('            left: 0;');
document.writeln('            width: 100%;');
document.writeln('            height: 100%;');
document.writeln('            display: flex;');
document.writeln('            align-items: center;');
document.writeln('            justify-content: center;');
document.writeln('            background: #000;');
document.writeln('        }');
document.writeln('        #flash-container {');
document.writeln('            position: relative;');
document.writeln('            max-width: 100%;');
document.writeln('            max-height: 100%;');
document.writeln('            box-shadow: 0 0 20px rgba(0,0,0,0.5);');
document.writeln('            transition: all 0.3s ease;');
document.writeln('        }');
document.writeln('        .flash-object {');
document.writeln('            display: block;');
document.writeln('            outline: none;');
document.writeln('        }');
document.writeln('        /* زر Fullscreen */');
document.writeln('        #fullscreen-btn {');
document.writeln('            position: fixed;');
document.writeln('            bottom: 20px;');
document.writeln('            right: 20px;');
document.writeln('            width: 50px;');
document.writeln('            height: 50px;');
document.writeln('            background-color: rgba(0, 0, 0, 0.7);');
document.writeln('            border: 2px solid #fff;');
document.writeln('            border-radius: 50%;');
document.writeln('            color: white;');
document.writeln('            font-size: 24px;');
document.writeln('            cursor: pointer;');
document.writeln('            z-index: 1000;');
document.writeln('            display: flex;');
document.writeln('            align-items: center;');
document.writeln('            justify-content: center;');
document.writeln('            transition: all 0.3s ease;');
document.writeln('            user-select: none;');
document.writeln('        }');
document.writeln('        #fullscreen-btn:hover {');
document.writeln('            background-color: rgba(50, 50, 50, 0.9);');
document.writeln('            transform: scale(1.1);');
document.writeln('        }');
document.writeln('        #fullscreen-btn:active {');
document.writeln('            transform: scale(0.95);');
document.writeln('        }');
document.writeln('        /* إخفاء الزر في وضع Fullscreen */');
document.writeln('        .fullscreen-mode #fullscreen-btn {');
document.writeln('            opacity: 0.7;');
document.writeln('        }');
document.writeln('        .fullscreen-mode #fullscreen-btn:hover {');
document.writeln('            opacity: 1;');
document.writeln('        }');
document.writeln('        /* رسائل المساعدة */');
document.writeln('        .help-text {');
document.writeln('            position: fixed;');
document.writeln('            bottom: 80px;');
document.writeln('            right: 20px;');
document.writeln('            background-color: rgba(0, 0, 0, 0.8);');
document.writeln('            color: white;');
document.writeln('            padding: 10px 15px;');
document.writeln('            border-radius: 5px;');
document.writeln('            font-size: 14px;');
document.writeln('            z-index: 999;');
document.writeln('            display: none;');
document.writeln('            max-width: 250px;');
document.writeln('        }');
document.writeln('        @media (max-width: 768px) {');
document.writeln('            #flash-container {');
document.writeln('                width: 100% !important;');
document.writeln('                height: auto !important;');
document.writeln('            }');
document.writeln('            #fullscreen-btn {');
document.writeln('                bottom: 15px;');
document.writeln('                right: 15px;');
document.writeln('                width: 45px;');
document.writeln('                height: 45px;');
document.writeln('                font-size: 20px;');
document.writeln('            }');
document.writeln('        }');
document.writeln('    </style>');
document.writeln('</head>');
document.writeln('<body>');
document.writeln('    <div id="flash-wrapper">');
document.writeln('        <div id="flash-container">');
document.writeln('            <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"');
document.writeln('                    codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0"');
document.writeln('                    id="flashContent"');
document.writeln('                    class="flash-object">');
document.writeln('                <param name="movie" value="container.swf?MediaID=' + MediaID + '" />');
document.writeln('                <param name="quality" value="high" />');
document.writeln('                <param name="allowScriptAccess" value="sameDomain" />');
document.writeln('                <param name="scale" value="noScale" />');
document.writeln('                <param name="bgcolor" value="#000000" />');
document.writeln('                <param name="wmode" value="opaque" />');
document.writeln('                <param name="allowFullScreen" value="true" />');
document.writeln('                <embed src="container.swf?MediaID=' + MediaID + '"');
document.writeln('                       quality="high"');
document.writeln('                       scale="noScale"');
document.writeln('                       bgcolor="#000000"');
document.writeln('                       wmode="opaque"');
document.writeln('                       allowFullScreen="true"');
document.writeln('                       name="flashContent"');
document.writeln('                       class="flash-object"');
document.writeln('                       type="application/x-shockwave-flash"');
document.writeln('                       pluginspage="http://www.macromedia.com/go/getflashplayer"');
document.writeln('                       allowScriptAccess="sameDomain" />');
document.writeln('            </object>');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('');
document.writeln('    <!-- زر Fullscreen -->');
document.writeln('    <div id="fullscreen-btn" title="ملء الشاشة / الخروج">');
document.writeln('        <span id="fullscreen-icon">⛶</span>');
document.writeln('    </div>');
document.writeln('');
document.writeln('    <!-- رسالة مساعدة -->');
document.writeln('    <div id="help-text" class="help-text">');
document.writeln('        اضغط F11 للخروج من وضع ملء الشاشة<br>');
document.writeln('        أو استخدم هذا الزر');
document.writeln('    </div>');
document.writeln('');
document.writeln('    <script>');
document.writeln('        (function() {');
document.writeln('            // العناصر الرئيسية');
document.writeln('            var flashContainer = document.getElementById("flash-container");');
document.writeln('            var flashWrapper = document.getElementById("flash-wrapper");');
document.writeln('            var flashObj = document.getElementById("flashContent");');
document.writeln('            var embedObj = document.querySelector(\'embed[name="flashContent"]\');');
document.writeln('            var fullscreenBtn = document.getElementById("fullscreen-btn");');
document.writeln('            var fullscreenIcon = document.getElementById("fullscreen-icon");');
document.writeln('            var helpText = document.getElementById("help-text");');
document.writeln('            ');
document.writeln('            var aspectRatio = ' + aspectRatio + ';');
document.writeln('            var isFullscreen = false;');
document.writeln('            var showHelpTimeout;');
document.writeln('            ');
document.writeln('            // دالة حساب الأبعاد');
document.writeln('            function calculateDimensions() {');
document.writeln('                var windowWidth = window.innerWidth;');
document.writeln('                var windowHeight = window.innerHeight;');
document.writeln('                ');
document.writeln('                // حساب الأبعاد بناءً على نسبة aspect ratio');
document.writeln('                var containerWidth = windowWidth;');
document.writeln('                var containerHeight = containerWidth / aspectRatio;');
document.writeln('                ');
document.writeln('                // إذا كان الارتفاع المحسوب أكبر من ارتفاع النافذة');
document.writeln('                if (containerHeight > windowHeight) {');
document.writeln('                    containerHeight = windowHeight;');
document.writeln('                    containerWidth = containerHeight * aspectRatio;');
document.writeln('                }');
document.writeln('                ');
document.writeln('                // تطبيق الأبعاد');
document.writeln('                flashContainer.style.width = containerWidth + "px";');
document.writeln('                flashContainer.style.height = containerHeight + "px";');
document.writeln('                ');
document.writeln('                // تطبيق الأبعاد على عناصر Flash');
document.writeln('                if (flashObj) {');
document.writeln('                    flashObj.width = containerWidth;');
document.writeln('                    flashObj.height = containerHeight;');
document.writeln('                }');
document.writeln('                ');
document.writeln('                if (embedObj) {');
document.writeln('                    embedObj.width = containerWidth;');
document.writeln('                    embedObj.height = containerHeight;');
document.writeln('                }');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // دالة Fullscreen');
document.writeln('            function toggleFullscreen() {');
document.writeln('                if (!isFullscreen) {');
document.writeln('                    // الدخول في وضع Fullscreen');
document.writeln('                    if (flashWrapper.requestFullscreen) {');
document.writeln('                        flashWrapper.requestFullscreen();');
document.writeln('                    } else if (flashWrapper.mozRequestFullScreen) { // Firefox */');
document.writeln('                        flashWrapper.mozRequestFullScreen();');
document.writeln('                    } else if (flashWrapper.webkitRequestFullscreen) { // Chrome, Safari & Opera */');
document.writeln('                        flashWrapper.webkitRequestFullscreen();');
document.writeln('                    } else if (flashWrapper.msRequestFullscreen) { // IE/Edge */');
document.writeln('                        flashWrapper.msRequestFullscreen();');
document.writeln('                    } else if (document.documentElement.requestFullscreen) {');
document.writeln('                        document.documentElement.requestFullscreen();');
document.writeln('                    }');
document.writeln('                    ');
document.writeln('                    // تحديث الوضع');
document.writeln('                    isFullscreen = true;');
document.writeln('                    fullscreenIcon.textContent = "❎";');
document.writeln('                    fullscreenBtn.title = "الخروج من وضع ملء الشاشة";');
document.writeln('                    document.body.classList.add("fullscreen-mode");');
document.writeln('                    ');
document.writeln('                    // إظهار رسالة المساعدة لمدة 5 ثوان');
document.writeln('                    showHelpMessage();');
document.writeln('                } else {');
document.writeln('                    // الخروج من وضع Fullscreen');
document.writeln('                    if (document.exitFullscreen) {');
document.writeln('                        document.exitFullscreen();');
document.writeln('                    } else if (document.mozCancelFullScreen) { // Firefox */');
document.writeln('                        document.mozCancelFullScreen();');
document.writeln('                    } else if (document.webkitExitFullscreen) { // Chrome, Safari & Opera */');
document.writeln('                        document.webkitExitFullscreen();');
document.writeln('                    } else if (document.msExitFullscreen) { // IE/Edge */');
document.writeln('                        document.msExitFullscreen();');
document.writeln('                    }');
document.writeln('                    ');
document.writeln('                    // تحديث الوضع');
document.writeln('                    isFullscreen = false;');
document.writeln('                    fullscreenIcon.textContent = "⛶";');
document.writeln('                    fullscreenBtn.title = "ملء الشاشة";');
document.writeln('                    document.body.classList.remove("fullscreen-mode");');
document.writeln('                    ');
document.writeln('                    // إخفاء رسالة المساعدة');
document.writeln('                    hideHelpMessage();');
document.writeln('                }');
document.writeln('                ');
document.writeln('                // إعادة حساب الأبعاد بعد تغيير وضع الشاشة');
document.writeln('                setTimeout(calculateDimensions, 100);');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // إظهار رسالة المساعدة');
document.writeln('            function showHelpMessage() {');
document.writeln('                helpText.style.display = "block";');
document.writeln('                ');
document.writeln('                // إخفاء الرسالة بعد 5 ثوان');
document.writeln('                clearTimeout(showHelpTimeout);');
document.writeln('                showHelpTimeout = setTimeout(hideHelpMessage, 5000);');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // إخفاء رسالة المساعدة');
document.writeln('            function hideHelpMessage() {');
document.writeln('                helpText.style.display = "none";');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // كشف تغييرات Fullscreen');
document.writeln('            document.addEventListener("fullscreenchange", handleFullscreenChange);');
document.writeln('            document.addEventListener("mozfullscreenchange", handleFullscreenChange);');
document.writeln('            document.addEventListener("webkitfullscreenchange", handleFullscreenChange);');
document.writeln('            document.addEventListener("msfullscreenchange", handleFullscreenChange);');
document.writeln('            ');
document.writeln('            function handleFullscreenChange() {');
document.writeln('                // التحقق من الوضع الحالي');
document.writeln('                var isCurrentlyFullscreen = !!(');
document.writeln('                    document.fullscreenElement ||');
document.writeln('                    document.mozFullScreenElement ||');
document.writeln('                    document.webkitFullscreenElement ||');
document.writeln('                    document.msFullscreenElement');
document.writeln('                );');
document.writeln('                ');
document.writeln('                if (isCurrentlyFullscreen !== isFullscreen) {');
document.writeln('                    isFullscreen = isCurrentlyFullscreen;');
document.writeln('                    ');
document.writeln('                    if (isFullscreen) {');
document.writeln('                        fullscreenIcon.textContent = "❎";');
document.writeln('                        fullscreenBtn.title = "الخروج من وضع ملء الشاشة";');
document.writeln('                        document.body.classList.add("fullscreen-mode");');
document.writeln('                        showHelpMessage();');
document.writeln('                    } else {');
document.writeln('                        fullscreenIcon.textContent = "⛶";');
document.writeln('                        fullscreenBtn.title = "ملء الشاشة";');
document.writeln('                        document.body.classList.remove("fullscreen-mode");');
document.writeln('                        hideHelpMessage();');
document.writeln('                    }');
document.writeln('                    ');
document.writeln('                    calculateDimensions();');
document.writeln('                }');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // كشف ضغط المفاتيح للخروج بـ ESC أو F11');
document.writeln('            document.addEventListener("keydown", function(e) {');
document.writeln('                // مفتاح ESC للخروج من Fullscreen');
document.writeln('                if (e.key === "Escape" && isFullscreen) {');
document.writeln('                    toggleFullscreen();');
document.writeln('                }');
document.writeln('                // مفتاح F11 للتبديل');
document.writeln('                if (e.key === "F11") {');
document.writeln('                    e.preventDefault(); // منع السلوك الافتراضي');
document.writeln('                    toggleFullscreen();');
document.writeln('                }');
document.writeln('            });');
document.writeln('            ');
document.writeln('            // أحداث الزر');
document.writeln('            fullscreenBtn.addEventListener("click", toggleFullscreen);');
document.writeln('            ');
document.writeln('            // إظهار/إخفاء رسالة المساعدة عند التمرير فوق الزر');
document.writeln('            fullscreenBtn.addEventListener("mouseenter", function() {');
document.writeln('                if (isFullscreen) {');
document.writeln('                    showHelpMessage();');
document.writeln('                }');
document.writeln('            });');
document.writeln('            ');
document.writeln('            fullscreenBtn.addEventListener("mouseleave", function() {');
document.writeln('                if (isFullscreen) {');
document.writeln('                    setTimeout(hideHelpMessage, 1000);');
document.writeln('                }');
document.writeln('            });');
document.writeln('            ');
document.writeln('            // استدعاء الدوال عند التحميل والتغييرات');
document.writeln('            window.addEventListener("load", calculateDimensions);');
document.writeln('            window.addEventListener("resize", calculateDimensions);');
document.writeln('            window.addEventListener("orientationchange", function() {');
document.writeln('                setTimeout(calculateDimensions, 300);');
document.writeln('            });');
document.writeln('            ');
document.writeln('            // استدعاء أولي');
document.writeln('            if (document.readyState === "complete") {');
document.writeln('                calculateDimensions();');
document.writeln('            } else {');
document.writeln('                document.addEventListener("DOMContentLoaded", calculateDimensions);');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // كشف Flash');
document.writeln('            setTimeout(function() {');
document.writeln('                var flashDetected = flashObj.readyState || embedObj.readyState;');
document.writeln('                if (!flashDetected) {');
document.writeln('                    var noFlashMsg = document.createElement("div");');
document.writeln('                    noFlashMsg.innerHTML = "<div style=\'color:white; padding:20px; text-align:center;\'>" +');
document.writeln('                        "<h3>Flash Player مطلوب</h3>" +');
document.writeln('                        "<p>يبدو أن Flash Player غير مثبت أو مفعل في متصفحك</p>" +');
document.writeln('                        "<p>يمكنك استخدام <a href=\'https://ruffle.rs/\' style=\'color:#4CAF50;\'>Ruffle</a> كمشغل بديل</p>" +');
document.writeln('                        "</div>";');
document.writeln('                    flashContainer.appendChild(noFlashMsg);');
document.writeln('                }');
document.writeln('            }, 3000);');
document.writeln('        })();');
document.writeln('    </script>');
document.writeln('</body>');
document.writeln('</html>');