var pos = document.URL.indexOf('?', 0) + 1;
var mediaURL = document.URL.substr(pos);
var MediaID = mediaURL.substr(8);
var MediaTitle = MediaID.substr(0, MediaID.length - 4);

// الأبعاد الافتراضية (يمكن تعديلها حسب محتواك)
var defaultWidth = 1024;
var defaultHeight = 768;
var aspectRatio = defaultWidth / defaultHeight;

document.writeln('<!DOCTYPE html>');
document.writeln('<html lang="ar">');
document.writeln('<head>');
document.writeln('    <meta charset="UTF-8">');
document.writeln('    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">');
document.writeln('    <title>eScience - ' + MediaTitle + '</title>');
document.writeln('    <style>');
document.writeln('        * { margin: 0; padding: 0; box-sizing: border-box; }');
document.writeln('        html, body {');
document.writeln('            width: 100%;');
document.writeln('            height: 100%;');
document.writeln('            overflow: hidden;');
document.writeln('            background-color: #000;');
document.writeln('            font-family: Arial, sans-serif;');
document.writeln('        }');
document.writeln('        #flash-wrapper {');
document.writeln('            position: fixed;');
document.writeln('            top: 0;');
document.writeln('            left: 0;');
document.writeln('            width: 100%;');
document.writeln('            height: 100%;');
document.writeln('            display: flex;');
document.writeln('            align-items: center;');
document.writeln('            justify-content: center;');
document.writeln('            background: #000;');
document.writeln('        }');
document.writeln('        #flash-container {');
document.writeln('            position: relative;');
document.writeln('            max-width: 100%;');
document.writeln('            max-height: 100%;');
document.writeln('            box-shadow: 0 0 20px rgba(0,0,0,0.5);');
document.writeln('        }');
document.writeln('        .flash-object {');
document.writeln('            display: block;');
document.writeln('            outline: none;');
document.writeln('        }');
document.writeln('        .loading {');
document.writeln('            color: white;');
document.writeln('            position: absolute;');
document.writeln('            top: 50%;');
document.writeln('            left: 50%;');
document.writeln('            transform: translate(-50%, -50%);');
document.writeln('            font-size: 18px;');
document.writeln('            z-index: 1;');
document.writeln('        }');
document.writeln('        @media (max-width: 768px) {');
document.writeln('            #flash-container {');
document.writeln('                width: 100% !important;');
document.writeln('                height: auto !important;');
document.writeln('            }');
document.writeln('        }');
document.writeln('    </style>');
document.writeln('</head>');
document.writeln('<body>');
document.writeln('    <div id="flash-wrapper">');
document.writeln('        <div id="flash-container">');
document.writeln('            <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"');
document.writeln('                    codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0"');
document.writeln('                    id="flashContent"');
document.writeln('                    class="flash-object">');
document.writeln('                <param name="movie" value="container.swf?MediaID=' + MediaID + '" />');
document.writeln('                <param name="quality" value="high" />');
document.writeln('                <param name="allowScriptAccess" value="sameDomain" />');
document.writeln('                <param name="scale" value="noScale" />');
document.writeln('                <param name="bgcolor" value="#000000" />');
document.writeln('                <param name="wmode" value="opaque" />');
document.writeln('                <param name="allowFullScreen" value="true" />');
document.writeln('                <embed src="container.swf?MediaID=' + MediaID + '"');
document.writeln('                       quality="high"');
document.writeln('                       scale="noScale"');
document.writeln('                       bgcolor="#000000"');
document.writeln('                       wmode="opaque"');
document.writeln('                       allowFullScreen="true"');
document.writeln('                       name="flashContent"');
document.writeln('                       class="flash-object"');
document.writeln('                       type="application/x-shockwave-flash"');
document.writeln('                       pluginspage="http://www.macromedia.com/go/getflashplayer"');
document.writeln('                       allowScriptAccess="sameDomain" />');
document.writeln('            </object>');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('');
document.writeln('    <script>');
document.writeln('        (function() {');
document.writeln('            var flashContainer = document.getElementById("flash-container");');
document.writeln('            var flashObj = document.getElementById("flashContent");');
document.writeln('            var embedObj = document.querySelector(\'embed[name="flashContent"]\');');
document.writeln('            ');
document.writeln('            var aspectRatio = ' + aspectRatio + '; // نسبة العرض إلى الارتفاع');
document.writeln('            ');
document.writeln('            function calculateDimensions() {');
document.writeln('                var windowWidth = window.innerWidth;');
document.writeln('                var windowHeight = window.innerHeight;');
document.writeln('                ');
document.writeln('                // حساب الأبعاد بناءً على نسبة aspect ratio');
document.writeln('                var containerWidth = windowWidth;');
document.writeln('                var containerHeight = containerWidth / aspectRatio;');
document.writeln('                ');
document.writeln('                // إذا كان الارتفاع المحسوب أكبر من ارتفاع النافذة');
document.writeln('                if (containerHeight > windowHeight) {');
document.writeln('                    containerHeight = windowHeight;');
document.writeln('                    containerWidth = containerHeight * aspectRatio;');
document.writeln('                }');
document.writeln('                ');
document.writeln('                // تطبيق الأبعاد');
document.writeln('                flashContainer.style.width = containerWidth + "px";');
document.writeln('                flashContainer.style.height = containerHeight + "px";');
document.writeln('                ');
document.writeln('                // تطبيق الأبعاد على عناصر Flash');
document.writeln('                if (flashObj) {');
document.writeln('                    flashObj.width = containerWidth;');
document.writeln('                    flashObj.height = containerHeight;');
document.writeln('                }');
document.writeln('                ');
document.writeln('                if (embedObj) {');
document.writeln('                    embedObj.width = containerWidth;');
document.writeln('                    embedObj.height = containerHeight;');
document.writeln('                }');
document.writeln('                ');
document.writeln('                // تسجيل الأبعاد للتشخيص (يمكن حذفها)');
document.writeln('                console.log("Window:", windowWidth + "x" + windowHeight);');
document.writeln('                console.log("Flash:", containerWidth + "x" + containerHeight);');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // استدعاء الدالة عند التحميل وعند تغيير حجم النافذة');
document.writeln('            window.addEventListener("load", calculateDimensions);');
document.writeln('            window.addEventListener("resize", calculateDimensions);');
document.writeln('            window.addEventListener("orientationchange", function() {');
document.writeln('                setTimeout(calculateDimensions, 300);');
document.writeln('            });');
document.writeln('            ');
document.writeln('            // استدعاء أولي فوري');
document.writeln('            if (document.readyState === "complete") {');
document.writeln('                calculateDimensions();');
document.writeln('            } else {');
document.writeln('                document.addEventListener("DOMContentLoaded", calculateDimensions);');
document.writeln('            }');
document.writeln('            ');
document.writeln('            // إضافة رسالة للمستخدم إذا كان Flash غير مثبت');
document.writeln('            setTimeout(function() {');
document.writeln('                var flashDetected = flashObj.readyState || embedObj.readyState;');
document.writeln('                if (!flashDetected) {');
document.writeln('                    var noFlashMsg = document.createElement("div");');
document.writeln('                    noFlashMsg.innerHTML = "<div style=\'color:white; padding:20px; text-align:center;\'>" +');
document.writeln('                        "<h3>Flash Player مطلوب</h3>" +');
document.writeln('                        "<p>يبدو أن Flash Player غير مثبت أو مفعل في متصفحك</p>" +');
document.writeln('                        "<p>يمكنك استخدام <a href=\'https://ruffle.rs/\' style=\'color:#4CAF50;\'>Ruffle</a> كمشغل بديل</p>" +');
document.writeln('                        "</div>";');
document.writeln('                    flashContainer.appendChild(noFlashMsg);');
document.writeln('                }');
document.writeln('            }, 3000);');
document.writeln('        })();');
document.writeln('    </script>');
document.writeln('</body>');
document.writeln('</html>');